### PR TITLE
Fix compilation errors reported in Eclipse Mars

### PR DESCRIPTION
**Pull request by Godin**
Prior to this change Eclipse 4.5.2 Mars (Build id: 20160218-0600) shows compilation errors in `com.mountainminds.eclemma.core`, `com.mountainminds.eclemma.core.test` and `com.mountainminds.eclemma.debug.ui.compatibility`.

Also

```
mvn clean verify \
    -Dimplicit-target \
    -Dplatform-repository-url=http://download.eclipse.org/releases/mars/
```

will stop at `com.mountainminds.eclemma.core` with inability to compile.

After this change the only remaining compilation error is in `com.mountainminds.eclemma.debug.ui.compatibility` and same Maven command will pass tests.

Result of opening of project in Eclipse 3.8 Juno is the same as before - only `com.mountainminds.eclemma.debug.ui.compatibility` contains compilation error - "cycle in the type hierarchy" what was done on purpose for compatibility with Eclipse < 3.8.

### CODE REVIEW

**Comment by Godin** [comment]
@marchof could you please review?

**Comment by marchof** [comment]
@Godin SupressWarning "unchecked" warning is not required at any of the places. It gives me a compiler warning with the 3.5 target. If I remove everything looks good.

Beside that:

- Compiles in Eclipse with 3.5 target
- Local Maven o.k.

**Comment by Godin** [comment]
@marchof for Mars it is exactly opposite - warning if no suppression 😆  but I removed "unchecked", will merge.

**Comment by marchof** [comment]
@Godin From my point the minimum supported version should be our default dev target. So code should compile for this version without warnings.

**Comment by Godin** [comment]
@marchof no pb.

A kind of off-topic - do you know how many users of EclEmma are on Eclipse 3.5 ? I guess this set is close to set of Java 5 users.

**Comment by marchof** [comment]
@Godin Well, AFAIK there are plenty of users out there forced o work with historic RAD versions... We can rise the bar when we're at Eclipse.org.
